name: Example Workflow 2

on: [push]

jobs:
  create-jira-ticket:
    runs-on: ubuntu-latest
    outputs:
      pr_title: ${{ steps.set-output.outputs.pr_title }}
    steps:
      - name: Set an output value
        id: set-output
        run: echo "pr_title=Hello World" >> $GITHUB_OUTPUT

  second-job:
    runs-on: ubuntu-latest
    needs: create-jira-ticket
    steps:
      - name: Use output from create-jira-ticket
        run: |
          echo "The value passed from create-jira-ticket is: ${{ needs.create-jira-ticket.outputs.pr_title }}"
